version: '3'

services:
  fastapi:
    build: api/
    ports: 
      - 8080:8080
    networks:
      - deploy_network
    container_name: api

  streamlit:
    build: webapp/
    depends_on:
      - fastapi
    ports: 
        - 8501:8501
    networks:
      - deploy_network
    container_name: webapp

networks:
  deploy_network:
    driver: bridge