version: '3'

services:
  fastapi:
    build:
      dockerfile: api\Dockerfile
    ports: 
      - 8000:8000
    networks:
      - deploy_network
    # image: api
    container_name: api

  streamlit:
    build:
      dockerfile: webapp\Dockerfile
    depends_on:
      - fastapi
    ports: 
        - 8501:8501
    networks:
      - deploy_network
    # image: webapp
    container_name: webapp

networks:
  deploy_network:
    driver: bridge