name: Run CI/CD pipeline 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # allow manual trigger  
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install test dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-cicd.txt
    - name: Test with pytest
      run: |
        make test
